### PR TITLE
adding run on repl.it badge

### PR DESCRIPTION
**Pull request by malteianlauterbach**
this commit was generated automatically on repl.it

### CODE REVIEW

**Comment by Ekultek** [comment]
This needs to be merged into dev-beta first

**Comment by malteianlauterbach** [comment]
okay, shall i sent in another pr into dev-beta?

**Comment by Ekultek** [comment]
@malteianlauterbach yes please that would probably be the best and easiest solution

**Comment by NullArray** [comment]
> okay, shall i sent in another pr into dev-beta?

If you could that'd be great. I'll review it once it's there. Lemme know if there are any issues.

**Review by AstroOrbis — APPROVED** [review]

**Pull request closed without merging**
