### PR TITLE
Added ability to limit number of hosts saved

### PR DESCRIPTION
**Pull request by ehlewis**
Once option 2 is selected the user is prompted whether they want the total number of hosts limited.
The chosen limit is passed to the target function, if the user decided not to have a limit nothing will be passed
If a limit is inputted then that many results are saved to the file.

### CODE REVIEW

**Comment by NullArray** [comment]
We're using the `dev-beta` branch from now on. That is the development branch. Please submit this PR again for the correct branch.

**Comment by ehlewis** [comment]
Fixed conflicts

**Comment by Ekultek** [comment]
still some conflicts in the trunk, fix them please

**Comment by ehlewis** [comment]
Resolved new conflicts

**Comment by Ekultek** [comment]
Looks good to me, @NullArray?

**Comment by NullArray** [comment]
Yep, looking good. Thanks for the PR @ehlewis and for reviewing the changes @Ekultek . Approved, and merged.

**Pull request merged**
