### PR TITLE
from __future__ import print_function

### PR DESCRIPTION
**Pull request by cclauss**
__print()__ is a function in modern Python.

Ran [futurize --stage1 -w autosploit.py](http://python-future.org/futurize_cheatsheet.html) and also ran [isort](https://pypi.python.org/pypi/isort) on the imports.

### CODE REVIEW

**Comment by NullArray** [comment]
What is the added value here?

**Comment by cclauss** [comment]
Python 2 [end of life](https://www.python.org/dev/peps/pep-0373/) is two years away.  We want autosploit to have a longer life than that so we should make sure that it runs on Python 3.

**Comment by Ekultek** [comment]
@cclauss python2 isn’t going anywhere. To many things rely on it, including but not limited to Linux OS systems.

**Comment by cclauss** [comment]
Like Ubuntu going Python 3 only we what?  https://wiki.ubuntu.com/Python

**Comment by Ekultek** [comment]
There are many more linux systems then Ubuntu. Also there are way to many things that use python2 for it to be reaching end of life. Look at the download differences between 2 and 3, for example. They've been trying to get rid of python2 for a few years, yet it's now at 2.7.14

**Comment by cclauss** [comment]
I am not recommending that AutoSploit should only run on Python 3.  I am recommending that AutoSploit should only run on _both_ Python 2 and Python 3.

**Comment by NullArray** [comment]
What ever the case there are conflicts in this Pull Request. I will be going over them today together with other issues and PR's. So i will get back to this in a bit.

**Pull request closed without merging**
