### PR TITLE
Added Install script

### PR DESCRIPTION
**Pull request by thehappydinoa**
Install script for Fedora and Debian

### CODE REVIEW

**Comment by Ekultek** [comment]
You need to check the environment variables for msfconsole if it does not exist in the env, install it into /opt

**Comment by Ekultek** [comment]
Just made a commit, fix the conflicts

**Comment by Ekultek** [comment]
looks good to me

**Comment by Ekultek** [comment]
@NullArray seems like on Twitter it's going to turn into a `do both` type of thing so here's the command that will do the same exact thing:

```
sudo -s << EOF
apt-get update
apt-get -y install git python2.7 python-pip postgresql apache2
pip2 install requests psutil
curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > /tmp/msfinstall && cd /tmp 
chmod 755 msfinstall && ./msfinstall
rm msfinstall
EOF
```

**Comment by Ekultek** [comment]
@thehappydinoa yo, this is gonna have to wait a few days till we get some more votes on what people wants. It's looking like it's gonna be a `both` sort of thing, but for now we gotta wait. Just plan on this being merged in a couple days

**Comment by thehappydinoa** [comment]
@Ekultek no rush

**Comment by NullArray** [comment]
No rush indeed, i set the poll to expire in a week, half of which is already over. Like @Ekultek said it looks like it's going to be both. So i expect to merge this pull. just waiting on the final results.

**Comment by Ekultek** [comment]
Calling it as both, 11 hours left

**Pull request merged**
