### PR TITLE
Update autosploit.py

### PR DESCRIPTION
**Pull request by notpike**
Pull Request from @AriSaastamoinen

### CODE REVIEW

**Comment by NullArray** [comment]
Lmao, i want to put it in but at the same time i wouldn't want to insult my users. Wut do?

**Comment by notpike** [comment]
Yah no worries, didn't expect it to be excepted. ;)

**Comment by an4cr0n** [comment]
Lmao

**Comment by Ekultek** [comment]
This should defiantly be done

**Comment by Ekultek** [comment]
Why has this not been merged yet? Lmao

**Comment by NullArray** [comment]
Lmao, it' s pretty humorous i'm not going to lie. There is a conflict in the PR though, furthermore, i would prefer to have this pushed to the `dev-beta` branch. Since we decided we are putting updates on that branch until we have a stable release for the updated version.

**Comment by Ekultek** [comment]
I really like this because it’s hilarious but there’s to many conflicts right now. I’m gonna close this down

**Pull request closed without merging**
