### PR TITLE
Updated usage to last version in README

### PR DESCRIPTION
**Pull request by scmanjarrez**
Was reading the README and realized some commands were missing, so I decided to update the README to the current usage in master.

### CODE REVIEW

**Comment by Ekultek** [comment]
Cool thanks dude, looks fine to me lemme get Null in here

**Comment by Ekultek** [comment]
@scmanjarrez your second commit is already done, rollback

**Comment by Ekultek** [comment]
Also, you need to push to dev-beta not master.

**Comment by scmanjarrez** [comment]
Ups, sorry, I did the second commit for self usage. Only wanted to make a PR of first commit.

**Pull request closed without merging**
