### PR TITLE
Updated Autosploit with Host List Options

### PR DESCRIPTION
**Pull request by hACkABUS**
Hi ive submitted the pull request with the changes so far, have just tested, seems to be working ok, let me know what you think or if there are any issues
cheers

### CODE REVIEW

**Comment by NullArray** [comment]
Thank you for your contribution. So far it's looking good. I'll have some more time after the weekend. Then i plan to add some changes including yours, and resolve a conflict i had in a Pull Request someone else has submitted. I'll combine the changes, adjust some things that i feel could use adjusting and update the readme to attribute your and the other dev's contributions properly as well.

I'll keep yo posted of course.

**Comment by hACkABUS** [comment]
brilliant look forward to your feedback

**Comment by Ekultek** [comment]
this whole thing is now a conflict, do you think you could fix it and merge it into the `dev-beta` branch?

**Comment by NullArray** [comment]
I think i will be closing this since we already have this type of functionality in the development version. The reply i made in this thread was from way back before we had what we do now in the dev branch.

**Pull request closed without merging**
