### PR TITLE
fix failed to validate RHOST

### PR DESCRIPTION
**Pull request by obetools**

### CODE REVIEW

**Comment by NullArray** [comment]
`RHOST` is not a valid option for some MSF modules. If we change it from `RHOSTS` to `RHOST` won't we be of risk at running into the same problem just with a different module?

**Comment by gimemypass** [comment]
I see.. well we need to find whits modules use witsch rhost or rhosts

**Comment by Ekultek** [comment]
All you have to do is update metasploit on your system.

**Comment by NullArray** [comment]
Can anyone confirm? I thought the box i had tested this on had the latest version of MSF. In any case today i will be going over the pull requests and adding some adjustments. So i may come back to this issue later in the day.

**Comment by Ekultek** [comment]
I'm closing this because it's a pull request with no value

**Pull request closed without merging**
