### PR TITLE
Added platform detection and support for OSX in service check and start

### PR DESCRIPTION
**Pull request by ehlewis**

### CODE REVIEW

**Comment by Ekultek** [comment]
https://github.com/NullArray/AutoSploit/pull/101/files#diff-95cae60d040344d5abdc9ce621087096R55

Put the brew into a bash script

**Comment by ehlewis** [comment]
What're you suggesting to do? Im not too familiar in this area
This is just a one liner to start the postgresql service, not too sure why it needs to be done through brew but apparently it does on OSX

**Comment by Ekultek** [comment]
Put the brew calls into bash scripts, that’s all you need to do. It has to be done through brew because macos doesn’t have apt/pacman/yum. Brew is the package manager for macos

**Comment by ehlewis** [comment]
Are you saying I should use subprocess instead of our cmdline?

**Comment by ehlewis** [comment]
Fixed, didn't see those initially

**Comment by Ekultek** [comment]
Remove the `sudo` calls for the OS X runs. Brew can’t be run with sudo on Yosemite and higher

**Pull request merged**
