### PR TITLE
Ops Updates

### PR DESCRIPTION
**Pull request by nma-io**
- Made more PEP8 compliant (not totally compliant, but its a start)
- Used string.format() instead of the + var + method for cleaner reading and handling incompatible types (prevent future bugs)
- Made notes around some security concerns (will also open issue ticket)
- Added Retrying module for the API code to address open issue
- Added requirements.txt file to make it easier to operate with virtualenv.

### CODE REVIEW

**Comment by NullArray** [comment]
Thank you for the contribution, i am currently also looking to merge the PR from @khast3x he made some changes that might conflict with the changes you added. I will review both PRs in a bit though. Thanks again.

**Comment by khast3x** [comment]
Added dockerfile, so this should not conflict. When this is merged I'll update the Dockerfile to install python packages from the `requirements.txt` directly

**Comment by NullArray** [comment]
Currently getting a conflict in this PR as well.

**Comment by khast3x** [comment]
Its because you're the admin with the only write access to `autosploit.py`. You'll have to merge manually as admin

**Comment by NullArray** [comment]
Right sorry, it's been a long day. I'll get back to this in a little while.

**Pull request closed without merging**
