### PR TITLE
Reduce amount of Code + Make modules modules instead of commands

### PR DESCRIPTION
**Pull request by nobubby**
I made a few extra changes this time because I couldn't help myself.

### CODE REVIEW

**Comment by nobubby** [comment]
Done.

**Comment by nobubby** [comment]
Gonna sneak in some more fixes here.

1. Someone, evidently under siege by heart attack, thought it was a good idea to write plaintext, world-readable shodan API key files onto the disk. I have removed this portion of the code and request a moment of silence for this person's health and well being.
2. Removed a ton of lines of code by creating a write_hosts(ip, overwrite) function.
3. Refactored the shodan API portion of the code to remove a need for awful global variables. 
4. Removed miscellaneous bugs that were littered throughout the program.
5. Fixed some needlessly repeated code
6. Changed some variable and function names

**Comment by Ekultek** [comment]
1. Conflicts
2. Why are we asking for an API key every single run instead of just encoding the key and calling it from an autosploit directory we make?

**Comment by Ekultek** [comment]
You’re going to need to rebase this if you want it merged. It will be closed in 72 hours

**Comment by NullArray** [comment]
I appreciate the fervor @Ekultek but setting deadlines for non-collaborators on an open source project seems a little over the top to me. @nobubby can take the time he wants to add the changes you requested. However, if by the time he does so the entire codebase has been changed again then it is up to him to resolve his contribution up until the official dev version.

**Comment by Ekultek** [comment]
Closing this

**Pull request closed without merging**
