### PR TITLE
fixed check_for_msf() to check in $PATH

### PR DESCRIPTION
**Pull request by atucom**
Changed the check_for_msf() function to search the $PATH for the msfconsole executable. It previously was searching for an environment variable named 'msfconsole'.

### CODE REVIEW

**Comment by Ekultek** [comment]
Yes because when msf is installed msfconsole is added to your ENV vars

**Comment by atucom** [comment]
I think that may be a package manager specific thing because I don't see a msfconsole var when I run env on my Kali VM nor on an ubuntu AWS Lightsail instance where I 'bundle install'ed metasploit from their git repo. 

I do however see it listed in my $PATH on both boxes.

**Comment by Ekultek** [comment]
Could be, we can edit it so that it’ll look for both?

**Comment by Ekultek** [comment]
`return os.getenv(“msfconsole”, False) or distutils.spawn.find_executable("msfconsole")` would work

**Comment by Ekultek** [comment]
The intended functionality for it is to check if `msfconsole` is in your ENV PATH, by getting the env-var for it. It will either return `False` in which case the ruby executable will have to be called on the `msfconsole` file (it doesn't come +x by default, that I'm aware of anyways). From there if it returns `False` it will call `ruby <PATH>/msfconsole <COMMANDS>`. If it returns anything other then `False` it will run as `msfconsole <COMMANDS>` assuming that you have the console in your PATH somewhere

Like I said `return os.getenv(“msfconsole”, False) or distutils.spawn.find_executable("msfconsole")` will work

**Comment by atucom** [comment]
Updated with new line

**Comment by Ekultek** [comment]
Merged

**Pull request merged**
