### PR TITLE
added execute permission to start_services

### PR DESCRIPTION
**Pull request by kimocoder**
* Added execute permission to start_services.sh to the tool doesn't halt when trying to execute it.

### CODE REVIEW

**Comment by Ekultek** [comment]
Why?

**Comment by Ekultek** [comment]
The tool doesn't hault when trying to start the services, it starts when the program begins. Adding the permissions for an executable does the same thing as doing `sudo bash <FILE>.sh` but reads from the shebang line.

**Comment by kimocoder** [comment]
tested it not long ago, but give me a moment I'll gi check it again.

**Comment by Ekultek** [comment]
Do this:

```
cat << _EOF > test.sh
#!/bin/bash
echo "this is a test"
_EOF
bash test.sh && chmod +x test.sh && ./test.sh`
```

The output will be:

```
this is a test
this is a test
```
The only difference is one is executable and one is not, see here:

```
-rwxr-xr-x  1 admin  staff          22 Apr  3 12:17 test.sh
-rw-r--r--  1 admin  staff           0 Apr  3 12:17 test1.sh
```

**Comment by kimocoder** [comment]
Re-producing it all gives this

screenshot from 2018-04-03 19-30-56

**Comment by Ekultek** [comment]
You have to run with `sudo` so we can see the process `PID`s

**Comment by Ekultek** [comment]
Or change your system permissions to allow your user access to the `PID`s

**Comment by kimocoder** [comment]
running as Kali root, using sudo would give the same output

**Comment by Ekultek** [comment]
I'm gonna go ahead and test this really quick

**Comment by kimocoder** [comment]
Quick fix! thanks sir

**Pull request merged**
